// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.finos.legend.engine.server.core.sql;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.apache.commons.io.IOUtils;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.charset.StandardCharsets;

@Api(tags = "SQL Documentation")
@Path("sql-docs")
public class SQLDocumentation
{
    private static final String CLASSPATH_PREFIX = "sql-docs/";
    private static final String DOC_SITE_PREFIX = CLASSPATH_PREFIX + "site/";

    @GET
    @Path("summary")
    @ApiOperation(value = "SQL coverage summary report")
    @Produces(MediaType.TEXT_HTML)
    public Response summary()
    {
        return serveHtml("summary.html");
    }

    @GET
    @Path("function-coverage")
    @ApiOperation(value = "SQL function coverage report")
    @Produces(MediaType.TEXT_HTML)
    public Response functionCoverage()
    {
        return serveHtml("function-coverage.html");
    }

    @GET
    @Path("structural-parity")
    @ApiOperation(value = "SQL structural parity report")
    @Produces(MediaType.TEXT_HTML)
    public Response structuralParity()
    {
        return serveHtml("structural-parity.html");
    }

    @GET
    @Path("failure-details")
    @ApiOperation(value = "SQL failure details report")
    @Produces(MediaType.TEXT_HTML)
    public Response failureDetails()
    {
        return serveHtml("failure-details.html");
    }

    /**
     * Serves the static documentation site generated by {@code DocumentationSiteGenerator}
     * (index.html, functions/*.html, operators/*.html, structural/*.html,
     * compositions/*.html, test/*.html, and assets/app.css + assets/app.js), bundled at
     * {@code sql-docs/site/**} on the classpath (see the e2e-tests module's
     * {@code copy-site} resource-plugin execution). Unlike the flat report
     * endpoints above, this is a catch-all so the whole directory tree ? including the
     * CSS/JS assets, which are not HTML ? is reachable and served with the right
     * content type. The path segment may be empty (i.e. a request ending in
     * {@code site/}), which is treated as {@code index.html}.
     */
    @GET
    @Path("site/{path: .*}")
    public Response documentationSiteAsset(@PathParam("path") String path)
    {
        String resolvedPath = (path == null || path.isEmpty()) ? "index.html" : path;
        String mediaType = mediaTypeFor(resolvedPath);
        byte[] bytes = loadBinaryResource(DOC_SITE_PREFIX + resolvedPath);
        if (bytes == null)
        {
            return Response.status(Response.Status.NOT_FOUND)
                    .type(MediaType.TEXT_HTML)
                    .entity("<html><body><h1>Report not available</h1>"
                            + "<p>The doc site asset <code>" + resolvedPath + "</code> has not been generated yet.</p>"
                            + "<p>Run the SQL E2E doc tests to generate it: "
                            + "<code>mvn verify -pl legend-engine-xts-sql/legend-engine-xt-sql-e2e-tests</code></p>"
                            + "</body></html>")
                    .build();
        }
        return Response.ok(bytes, mediaType).build();
    }

    /**
     * Redirects {@code sql-docs/site} (no trailing slash) to
     * {@code sql-docs/site/index.html}. This must be a real redirect rather than
     * serving {@code index.html}'s bytes directly at the bare URL: browsers resolve the
     * page's relative links/assets (e.g. {@code assets/app.css}, {@code functions/string.html})
     * against the address-bar path, treating the last segment as a directory only if the
     * URL ends in {@code /}. Serving the content at {@code .../site} (no slash) made
     * every relative reference resolve one level too shallow, e.g.
     * {@code .../sql-docs/assets/app.css} instead of {@code .../sql-docs/site/assets/app.css}.
     */
    @GET
    @Path("site")
    public Response documentationSite(@Context UriInfo uriInfo)
    {
        URI target = uriInfo.getAbsolutePathBuilder().path("index.html").build();
        return Response.seeOther(target).build();
    }

    private static String mediaTypeFor(String path)
    {
        int dot = path.lastIndexOf('.');
        String extension = dot >= 0 ? path.substring(dot + 1).toLowerCase() : "";
        switch (extension)
        {
            case "html":
                return MediaType.TEXT_HTML;
            case "css":
                return "text/css";
            case "js":
                return "application/javascript";
            case "json":
                return MediaType.APPLICATION_JSON;
            case "svg":
                return "image/svg+xml";
            default:
                return MediaType.APPLICATION_OCTET_STREAM;
        }
    }

    private Response serveHtml(String fileName)
    {
        return serveFile(fileName, MediaType.TEXT_HTML);
    }

    private Response serveFile(String fileName, String mediaType)
    {
        String content = loadResource(fileName);
        if (content == null)
        {
            return Response.status(Response.Status.NOT_FOUND)
                    .type(MediaType.TEXT_HTML)
                    .entity("<html><body><h1>Report not available</h1>"
                            + "<p>The report <code>" + fileName + "</code> has not been generated yet.</p>"
                            + "<p>Run the SQL E2E doc tests to generate it: "
                            + "<code>mvn verify -pl legend-engine-xts-sql/legend-engine-xt-sql-e2e-tests</code></p>"
                            + "</body></html>")
                    .build();
        }
        return Response.ok(content, mediaType).build();
    }

    private String loadResource(String fileName)
    {
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(CLASSPATH_PREFIX + fileName);
        if (is == null)
        {
            return null;
        }
        try (InputStream stream = is)
        {
            return IOUtils.toString(stream, StandardCharsets.UTF_8);
        }
        catch (IOException e)
        {
            return null;
        }
    }

    private byte[] loadBinaryResource(String classpathPath)
    {
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(classpathPath);
        if (is == null)
        {
            return null;
        }
        try (InputStream stream = is)
        {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            IOUtils.copy(stream, out);
            return out.toByteArray();
        }
        catch (IOException e)
        {
            return null;
        }
    }
}
