# Project identification
sonar.projectKey=legend-engine
sonar.organization=finos
sonar.projectName=Legend Engine

# Source configuration
sonar.sources=.
sonar.inclusions=**/src/main/java/**

# Test configuration
sonar.tests=.
sonar.test.inclusions=**/src/test/java/**

# Binaries (standard Maven compiled output)
sonar.java.binaries= **/target/classes/**,**/target/*.jar,**/pom.xml

# Encoding
sonar.sourceEncoding=UTF-8
