# Copyright 2022 Goldman Sachs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release (Large Runner)

env:
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
  DOCKER_USERNAME: finos
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MAVEN_OPTS: -Xmx36g
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "New release version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINOS_GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.email "37706051+finos-admin@users.noreply.github.com"
          git config --global user.name "FINOS Administrator"

      - name: Set up Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
          server-id: central
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpg-passphrase: CI_GPG_PASSPHRASE

      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          theme: dark

      - name: Build and install
        run: |
          mvn -B -e -T4 -DskipTests -Dorg.slf4j.simpleLogger.showThreadName=true \
            -Drevision=${{ github.event.inputs.releaseVersion }} \
            install -P release,docker,pct-cloud-test

      - name: Deploy to Central
        run: |
          mvn -B -e -T4 -Drevision=${{ github.event.inputs.releaseVersion }} \
            deploy -P release,docker,pct-cloud-test

      - name: Create and push git tag
        run: |
          git tag ${{ github.event.repository.name }}-${{ github.event.inputs.releaseVersion }}
          git push origin ${{ github.event.repository.name }}-${{ github.event.inputs.releaseVersion }}

      - name: Compute and set next SNAPSHOT
        run: |
          releaseVersion=${{ github.event.inputs.releaseVersion }}
          n=${releaseVersion//[!0-9]/ }
          a=(${n//\./ })
          nextPatch=$((${a[2]} + 1))
          nextSnapshot="${a[0]}.${a[1]}.${nextPatch}-SNAPSHOT"
          sed -i "s|<revision>.*</revision>|<revision>${nextSnapshot}</revision>|" pom.xml
          git add pom.xml
          git commit -m "Bump version to ${nextSnapshot}"
          git push origin master
